theme: jekyll-theme-hacker

encoding: UTF-8
timezone: Ljubljana

# Name of your site (displayed in the header)
name: QA Tool Kit
logo: https://avatars2.githubusercontent.com/u/73333202?s=200&v=4
title: QA Tool Kit
description: Tools, scripts, libraries and guides for your QA tasks
absolute_url: https://qatoolkit.io
github:
  is_project_page: true
  is_user_page: false
show_downloads: false