theme: jekyll-theme-minimal

encoding: UTF-8
timezone: Ljubljana
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: QAToolKit
logo: https://avatars2.githubusercontent.com/u/73333202?s=200&v=4
title: QAToolKit
description: Tools for your QA tasks
absolute_url: https://qatoolkit.io
github:
  is_project_page: true
  is_user_page: false
show_downloads: false